import User from "../models/User.js";
import jwt from "jsonwebtoken";
import { sendOtpEmail, sendOtpWhatsApp } from "../utils/otpUtils.js";

// Generate JWT
const generateToken = (id) => {
  return jwt.sign({ id }, process.env.JWT_SECRET, { expiresIn: "7d" });
};

// Signup
export const signup = async (req, res) => {
  const { name, email, password, phone, location } = req.body;

  try {
    const userExists = await User.findOne({ email });
    if (userExists) return res.status(400).json({ message: "User already exists" });

    const user = await User.create({ name, email, password, phone, place: location });

    // Send OTP to Email
    const otp = Math.floor(100000 + Math.random() * 900000).toString();
    await sendOtpEmail(email, otp);

    user.otp = otp;
    await user.save();

    res.status(201).json({
      message: "User created, OTP sent to email",
      userId: user._id,
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Signup failed" });
  }
};

// Login
export const login = async (req, res) => {
  const { email, password } = req.body;

  try {
    const user = await User.findOne({ email });
    if (!user) return res.status(404).json({ message: "User not found" });

    const isMatch = await user.matchPassword(password);
    if (!isMatch) return res.status(401).json({ message: "Invalid password" });

    res.status(200).json({
      token: generateToken(user._id),
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        phone: user.phone,
      },
      message: "Login successful"
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Login failed" });
  }
};

// Forgot Password
export const forgotPassword = async (req, res) => {
  const { email } = req.body;
  try {
    const user = await User.findOne({ email });
    if (!user) return res.status(404).json({ message: "User not found" });

    const otp = sendOtpEmail(email, Math.floor(100000 + Math.random() * 900000).toString());

    // We can reuse the OTP field or create a new one. Using existing OTP field for simplicity
    // Ideally we should have a separate field or a flag, but for now this works as "latest OTP"
    // Since we are sending it via email, we just need to save the OTP generated by the util (Wait, util returns void in the current stub? No, I updated it to return nothing but send email. I should fix logic.)

    // Correction: My updated sendOtpEmail in previous step was async and didn't return the OTP. 
    // I need to generate OTP here and pass it to sendOtpEmail.
    const generatedOtp = Math.floor(100000 + Math.random() * 900000).toString();
    await sendOtpEmail(email, generatedOtp);

    user.otp = generatedOtp;
    await user.save();

    res.status(200).json({ message: "OTP sent to your email" });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Error sending OTP" });
  }
};

// Reset Password
export const resetPassword = async (req, res) => {
  const { email, otp, newPassword } = req.body;
  try {
    const user = await User.findOne({ email });
    if (!user) return res.status(404).json({ message: "User not found" });

    if (user.otp !== otp) {
      return res.status(400).json({ message: "Invalid OTP" });
    }

    user.password = newPassword; // Will be hashed by pre-save hook
    user.otp = null; // Clear OTP
    await user.save();

    res.status(200).json({ message: "Password reset successfully" });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Error resetting password" });
  }
};

// Social Auth Callback
export const socialAuthCallback = (req, res) => {
  // Req.user is populated by passport
  const token = generateToken(req.user._id);
  // Redirect to frontend with token
  // Assuming frontend is running on port 5173 (Vite default)
  res.redirect(`http://localhost:5173/auth/social?token=${token}`);
};

// Verify OTP
export const verifyOtp = async (req, res) => {
  const { userId, otp } = req.body;

  try {
    const user = await User.findById(userId);
    if (!user) return res.status(404).json({ message: "User not found" });

    if (user.otp !== otp) {
      return res.status(400).json({ message: "Invalid OTP" });
    }

    // OTP verified, clear it
    user.otp = null;
    await user.save();

    res.status(200).json({
      token: generateToken(user._id),
      user: {
        id: user._id,
        name: user.name,
        email: user.email,
        phone: user.phone,
        place: user.place,
      },
      message: "OTP verified successfully",
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "OTP verification failed" });
  }
};

// Get User Profile
export const getProfile = async (req, res) => {
  try {
    const user = await User.findById(req.user._id).select("-password -otp");
    if (!user) return res.status(404).json({ message: "User not found" });
    res.status(200).json(user);
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Error fetching profile" });
  }
};

// Update User Profile
export const updateProfile = async (req, res) => {
  const { name, phone, place } = req.body;
  try {
    const user = await User.findById(req.user._id);
    if (!user) return res.status(404).json({ message: "User not found" });

    user.name = name || user.name;
    user.phone = phone || user.phone;
    user.place = place || user.place;

    const updatedUser = await user.save();

    res.status(200).json({
      _id: updatedUser._id,
      name: updatedUser.name,
      email: updatedUser.email,
      phone: updatedUser.phone,
      place: updatedUser.place,
      role: updatedUser.role,
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Error updating profile" });
  }
};
